# Generated by Django 4.0.4 on 2022-04-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='author',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
