# Generated by Django 4.0.3 on 2022-05-01 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_players_number_of_reviews_reviews_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='nickname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='number_of_reviews',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='accepted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='players.players'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
