# Generated by Django 4.0.3 on 2022-05-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_players_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='date_of_submit',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='image_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
